on: ["push"]
name: Coverage
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.17.1
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - uses: actions/cache@v2
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  node-version: 16.17.1
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - run: yarn install
            - run: yarn compile
    unit-tests:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - run: yarn coverage
          - name: Unit test coveralls
            uses: coverallsapp/github-action@master
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                parallel: true
    fork-tests:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: create env file
            run: |
                touch .env
                echo NODE_URL=${{ secrets.NODE_URL }} >> .env
          - run: yarn coverage:fork
          - name: Fork test coveralls
            uses: coverallsapp/github-action@master
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                parallel: true
    finish:
        needs: [unit-tests, fork-tests]
        runs-on: ubuntu-latest
        steps:
        - name: Coveralls Finished
          uses: coverallsapp/github-action@master
          with:
              github-token: ${{ secrets.github_token }}
              parallel-finished: true